// <auto-generated />
using System;
using Apache.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apache.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Apache.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Apache.Models.CheckDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ChecksId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("ProductsPrihodId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecksId");

                    b.HasIndex("ProductsPrihodId");

                    b.ToTable("CheckDetails");
                });

            modelBuilder.Entity("Apache.Models.Checks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CheckNum")
                        .HasColumnType("bigint");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int?>("PlacesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrintDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("StaffsId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PlacesId");

                    b.HasIndex("StaffsId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("Apache.Models.Places", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Apache.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Apache.Models.ProductsPrihod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ComeQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PrihodDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductsPrihod");
                });

            modelBuilder.Entity("Apache.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Apache.Models.Staffs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Apache.Models.CheckDetails", b =>
                {
                    b.HasOne("Apache.Models.Checks", null)
                        .WithMany("CheckDetails")
                        .HasForeignKey("ChecksId");

                    b.HasOne("Apache.Models.ProductsPrihod", "ProductsPrihod")
                        .WithMany()
                        .HasForeignKey("ProductsPrihodId");

                    b.Navigation("ProductsPrihod");
                });

            modelBuilder.Entity("Apache.Models.Checks", b =>
                {
                    b.HasOne("Apache.Models.Places", "Places")
                        .WithMany()
                        .HasForeignKey("PlacesId");

                    b.HasOne("Apache.Models.Staffs", "Staffs")
                        .WithMany()
                        .HasForeignKey("StaffsId");

                    b.Navigation("Places");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Apache.Models.Products", b =>
                {
                    b.HasOne("Apache.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Apache.Models.ProductsPrihod", b =>
                {
                    b.HasOne("Apache.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsId");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Apache.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Apache.Models.Checks", b =>
                {
                    b.Navigation("CheckDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
